spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/finance_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false      # SQL controlado pelo Log4j2 via org.hibernate.SQL logger
    properties:
      hibernate:
        format_sql: true
        highlight_sql: false  # desabilita ANSI no SQL para acessibilidade